dist: trusty
sudo: false

language: python

cache:
  directories:
  - $HOME/.cache/pip

matrix:
  include:
    - env: PYTHON_VERSION="3.7" NUMPY_VERSION="1.16.6" SCIPY_VERSION="1.4.1"
           SKLEARN_VERSION="0.20.3"
    - env: PYTHON_VERSION="3.8" NUMPY_VERSION="*" SCIPY_VERSION="*"
           SKLEARN_VERSION="*"
    - env: PYTHON_VERSION="3.8" NUMPY_VERSION="*" SCIPY_VERSION="*"
           SKLEARN_VERSION="*" COVERAGE="true"

install:
  # install miniconda
  - deactivate
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - MINICONDA_PATH=/home/travis/miniconda
  - chmod +x miniconda.sh && ./miniconda.sh -b -p $MINICONDA_PATH
  - export PATH=$MINICONDA_PATH/bin:$PATH
  - conda update --yes conda
  # create the testing environment
  - conda create -n testenv --yes python=$PYTHON_VERSION pip
  - source activate testenv
  - |
      if [ $SKLEARN_VERSION = "nightly" ]; then
          conda install --yes numpy==$NUMPY_VERSION scipy==$SCIPY_VERSION cython nose pytest pytest-cov
          # install nightly wheels
          pip install --pre -f https://sklearn-nightly.scdn8.secure.raxcdn.com scikit-learn
      else
          conda install --yes numpy==$NUMPY_VERSION scipy==$SCIPY_VERSION scikit-learn==$SKLEARN_VERSION cython nose pytest pytest-cov
      fi
  - conda install --yes pandas numba
  - pip install codecov
  - pip install hypothesis
  - pip install coverage
  - pip install coveralls
  - pip install .

script:
  - |
      if [ "$COVERAGE" = "true" ]; then
         # disable numba for coverage run
         export NUMBA_DISABLE_JIT=1
         coverage run -m pytest -v --pyargs vectorizers -k tests
      else
         pytest -v --pyargs vectorizers
      fi
after_success:
  - |
      if [ "$COVERAGE" = "true" ]; then
         codecov
         coveralls
      fi